name: 'Parse Changed Java Methods'
description: 'A custom action to detect changed Java files and parse methods.'

inputs:
  staged:
    description: 'Check staged (uncommitted) changes instead of committed changes'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose mode'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download or Use the Executable
      run: |
        mkdir -p /tmp/digma
        curl -L https://github.com/digma-ai/digma/raw/refs/heads/main/dev/tools/java-diff-linux-x64 -o /tmp/digma/java-diff
        chmod +x /tmp/digma/java-diff
      shell: bash  # Specify shell

    - name: Detect changed Java files and parse methods
      run: |
        if [ "${{ inputs.staged }}" = "true" ]; then
          changed_files=$(git diff --cached --name-only | grep '.java')
        else
          changed_files=$(git diff --name-only HEAD~1 HEAD | grep '.java')
        fi

        if [ -z "$changed_files" ]; then
          echo "No committed Java files changed."
          exit 0
        fi

        echo "$changed_files" | xargs /tmp/digma/java-diff --verbose=${{ inputs.verbose }}
      shell: bash  # Specify shell

    - name: Upload the CSV with methods
      uses: actions/upload-artifact@v3
      with:
        name: changed_codeobjects
        path: changed_codeobjects.csv