name: 'Parse Changed Java Methods'
description: 'A custom action to detect changed Java files and parse methods using Go.'

inputs:
  base_ref:
    description: 'The base branch in the pull request'
    required: true
  head_ref:
    description: 'The head branch in the pull request'
    required: true
  staged:
    description: 'Check staged (uncommitted) changes instead of committed changes'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to enable proper diff

    - name: Fetch PR branches
      run: |
        git fetch origin "${{ inputs.base_ref }}"  # Fetch the base (destination) branch
        git fetch origin "${{ inputs.head_ref }}"  # Fetch the head (source) branch
      shell: bash

    - name: Download or Use the Executable
      run: |
        mkdir -p /tmp/digma
        curl -L https://github.com/digma-ai/digma/raw/refs/heads/main/dev/tools/java-diff-linux-x64 -o /tmp/digma/java-diff
        chmod +x /tmp/digma/java-diff
      shell: bash

    - name: Detect changed Java files and parse methods
      run: |
        if [ "${{ inputs.staged }}" = "true" ]; then
          changed_files=$(git diff --cached --name-only | grep '.java')
        else
          changed_files=$(git diff --name-only origin/${{ inputs.base_ref }}...origin/${{ inputs.head_ref }} | grep '.java')
        fi

        echo "Changed files: $changed_files"

        if [ -z "$changed_files" ]; then
          echo "No committed Java files changed."
          exit 0
        fi

        # Run the diff tool on the changed files
        echo "$changed_files" | xargs /tmp/digma/java-diff --base-ref=${{ inputs.base_ref }} --head-ref=${{ inputs.head_ref }} --verbose=${{ inputs.verbose }}
      shell: bash

    - name: Upload the CSV with methods
      uses: actions/upload-artifact@v3
      with:
        name: changed_codeobjects
        path: changed_codeobjects.csv