name: 'API Call and Parse JSON'
description: 'Calls an API using a configurable domain, parses the JSON response, and fails the job if insights are found.'
inputs:
  digma_url:
    description: 'The Digma API to call'
    required: true
  api_token:
    description: 'Authorization token for API access'
    required: true
  user_name:
    description: 'Digma user'
    required: true
  password:
    description: 'Digma password'
    required: true
  environment_id:
    description: 'Digma environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Call API and Check Response
      shell: bash
      run: |
        user="${{ inputs.user_name }}"
        password="${{ inputs.password }}"
        api_token="${{ inputs.api_token }}"
        domain="${{ inputs.digma_url }}"

       # Make the POST request and store the response
        RESPONSE=$(curl -s -X POST "${domain}/authentication/login" \
          -H "Digma-Access-Token: Token $api_token" \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          -d '{"username":"'"$user"'","password":"'"$password"'"}')

        # Parse the access token from the response
        access_token=$(echo $RESPONSE | jq -r '.accessToken')

        response=$(curl -X 'GET' \
          "${domain}/Insights/get_insights_view?Page=0&PageSize=2&ShowDismissed=false&ShowUnreadOnly=false&DirectOnly=false&Environment=${environment_id}&InsightViewType=Issues" \
          -H 'accept: application/json' \
          -H "Digma-Access-Token: Token $api_token" \
          -H "Authorization: Bearer $access_token" \
          -s)
        echo "$response" | jq . > response.json  # Save the formatted JSON to a file
      
        if jq -e '.insights | length > 0' response.json > /dev/null; then
          jq -r '.insights[] | "* \(.type):  \"\(.spanInfo.displayName)\""' response.json
          echo "::error ::Found new issues"
          exit 1
        else
          echo "No new issues found"
        fi  # This is where the 'if' block is closed
