name: 'Digma Java OTEL Instrumentation'
description: 'Adds instrumentation for sending Java OTEL traces to Digma'
inputs:
  collector_url:
    description: 'URL of the Digma OTEL collector backend'
    required: true
  service_name:
    description: 'The name of the application being observed'
    required: true
  environment:
    description: 'The Digma environment name for this execution'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download agent jar
      shell: bash
      run: |
        mkdir -p /tmp/otel
        curl -L https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar -o /tmp/otel/opentelemetry-javaagent.jar
    
    - name: Download extension jar
      shell: bash
      run: |
        mkdir -p /tmp/otel
        curl -L https://github.com/digma-ai/otel-java-instrumentation/releases/latest/download/digma-otel-agent-extension.jar -o /tmp/otel/digma-otel-agent-extension.jar
    
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "JAVA_TOOL_OPTIONS=-javaagent:/tmp/otel/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=${{ inputs.collector_url }} -Dotel.javaagent.extensions=/tmp/otel/digma-otel-agent-extension.jar -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.exporter.otlp.protocol=grpc" >> $GITHUB_ENV
        echo "OTEL_SERVICE_NAME=${{ inputs.service_name }}" >> $GITHUB_ENV
        echo "OTEL_RESOURCE_ATTRIBUTES=digma.environment=${{ inputs.environment }},digma.environment.type=Public" >> $GITHUB_ENV
